### ISSUE TITLE
rust version 1.28 forwards seems to break new array creation

### ISSUE THREAD

**Issue by Aidan24** [arrayfire/arrayfire-rust#176] opened 2018-08-04 18:08 UTC
From rust version 1.28.0 forwards statements that create new arrays like
 let weights: af::Array = randu::<f64>(wdims);
fail at runtime for me. Downgrading to 1.27.2 and below they work again. I have tried multiple versions of the arrayfire wrapper and different versions of Arrayfire and it doesn't seem to make a difference. 

Windows 10 version 1803 build 17134.191
2017 C++ buildtools

**Comment by 9prady9** [comment] 2018-08-05 01:43
@Aidan24 Thank you for reporting this. I will check 3.5.0 release tag against 1.28.0 rust version. I am surprised though about how rust version increment is breaking the crate at runtime and not at compile time.

I would also like you to know that, I have been working on typed arrays (#175) for the past couple of days. I can assure you that 3.6.0 (being worked on #175 - will be released in couple of days) is not failing with rust 1.28.0.

**Comment by 9prady9** [comment] 2018-08-05 03:31
I have tried 3.5.0 with rust-1.28.0 on Arch Linux and that didn't have any issue. May be it is a problem with MSVC toolchain only.

**Comment by Aidan24** [comment] 2018-08-05 07:33
@9prady9 Thanks for looking into this. I think you're right, it's probably a windows related thing. At first I assumed it was either an Nvidia drivers update or a Windows update that caused it as BACTRACE=1 pinpointed a new_empty statement failing first. Then after trying other simpler, previously fine, code it looks like anything that actually allocates memory fails. Creating a constant array doesn't seem to fail, but I assume this doesn't actually allocate any space.

Unfortunately I already tried putting arrayfire = { git = "https://github.com/arrayfire/arrayfire-rust" } in the dependencies and it 3.6.0 didn't work for me either. It was only when I tried earlier versions of rust itself that the runtime problem goes away (as far as I can tell everything before 1.28.0 - I only tested back to 1.16.0 - works). I'm sorry I'm not much use in helping, I'm very new to rust generally.

If there's anything else I can tell you that might help let me know.

**Comment by 9prady9** [comment] 2018-08-05 07:51
From what you have experienced, it definitely looks like the problem is specific to MSVC toolchain. Sure, I will let you know if there is anything else that you can help out here.

**Comment by 9prady9** [comment] 2018-08-14 19:30
We don't test it with GNU toolchain in Windows, so I don't really have much data on how GNU toolchain on windows works for rust.

I won't be working for next week or so on this, but I will get back to it once I resume work. Thanks for sharing the feedback.

**Comment by Aidan24** [comment] 2018-09-12 11:09
Probably should add that the exit code is 3221225501 and that it still exists with the latest nightly build.

**Comment by 9prady9** [comment] 2018-09-17 06:56
@Aidan24 Have you tried it again with Rust 1.29 ?

**Comment by Aidan24** [comment] 2018-09-17 11:47
Hi 9prady9 yes and it doesn't work for me. For a more concrete example here is an example code and output, first from 1.27.2 then from the latest stable. The results are the same from nightly too:

`extern crate arrayfire as af;
use af::*;

fn main() {
    let num_rows: u64 = 8;
    let num_cols: u64 = 8;
    let dims = Dim4::new(&[num_rows, num_cols, 1, 1]);
    let be:Backend = Backend::OPENCL; //CPU, CUDA, OPENCL
    
    println!("Create a {}-by-{} matrix of random 32 bit floats on the {}", num_rows, num_cols, be);
 
    af::set_backend(be);
    println!("dims = {}", dims);

    let a = randu::<f32>(dims);
    af_print!("a = ", a);

    println!("Device info {:?}",af::get_available_backends());
    println!("Active device {:?}",af::get_active_backend());
}`

**Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\Users\gibsona\rust\af_test> rustup default 1.27.2
info: using existing install for '1.27.2-x86_64-pc-windows-msvc'
info: default toolchain set to '1.27.2-x86_64-pc-windows-msvc'

  1.27.2-x86_64-pc-windows-msvc unchanged - rustc 1.27.2 (58cc626de 2018-07-18)

PS C:\Users\gibsona\rust\af_test> cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.16s
     Running `target\debug\af_test.exe`
Create a 8-by-8 matrix of random 32 bit floats on the OpenCL
dims = [8 8 1 1]
a =
[8 8 1 1]
    0.6010     0.7509     0.4165     0.7896     0.3336     0.7917     0.3637     0.6353
    0.0278     0.4105     0.5814     0.8966     0.0363     0.1654     0.9643     0.7449
    0.9806     0.1583     0.8962     0.0536     0.5349     0.8657     0.9092     0.4391
    0.2126     0.3712     0.3712     0.5775     0.0123     0.3766     0.8865     0.6982
    0.0655     0.3543     0.6755     0.2908     0.3988     0.7331     0.9676     0.5970
    0.5497     0.6450     0.6105     0.9941     0.9787     0.2522     0.1425     0.9594
    0.2864     0.9675     0.5232     0.5143     0.2308     0.9644     0.5137     0.2323
    0.3410     0.3636     0.5567     0.3670     0.6244     0.4711     0.6484     0.9623

Device info [OPENCL, CUDA, CPU]
Active device OPENCL
PS C:\Users\gibsona\rust\af_test> rustup default stable
info: using existing install for 'stable-x86_64-pc-windows-msvc'
info: default toolchain set to 'stable-x86_64-pc-windows-msvc'

  stable-x86_64-pc-windows-msvc unchanged - rustc 1.29.0 (aa3ca1994 2018-09-11)

PS C:\Users\gibsona\rust\af_test> cargo run
   Compiling af_test v0.1.0 (file:///C:/Users/gibsona/rust/af_test)
    Finished dev [unoptimized + debuginfo] target(s) in 0.89s
     Running `target\debug\af_test.exe`
Create a 8-by-8 matrix of random 32 bit floats on the OpenCL
dims = [8 8 1 1]
error: process didn't exit successfully: `target\debug\af_test.exe` (exit code: 3221225501)
PS C:\Users\gibsona\rust\af_test>**

**Comment by 9prady9** [comment] 2018-09-17 12:38
@Aidan24 Would it be possible for you to try your example with the changes from PR #175 and please let me know how that works out.

**Comment by Aidan24** [comment] 2018-09-17 12:45
@9prady9 How do I do that? In the dependencies I'm using the below:

[dependencies]
arrayfire = { git = "https://github.com/arrayfire/arrayfire-rust" }

So I think I'm using the latest 3.6 version.

**Comment by 9prady9** [comment] 2018-09-17 13:17
The PR hasn't been merged as I have requested community feedback on [slack](https://join.slack.com/t/arrayfire-org/shared_invite/MjI4MjIzMDMzMTczLTE1MDI5ODg4NzYtN2QwNGE3ODA5OQ) channel. 

you can use the following instead of what you have now
```
arrayfire = { git = "https://github.com/9prady9/arrayfire-rust", branch = "typed_arrays" }
```

These changes might break some of your code as Arrays are typed/generic over a given type now. If you have any trouble compiling, please let me know.

**Comment by Aidan24** [comment] 2018-09-17 13:54
Sorry no that didn't work for me:

Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\Users\gibsona\rust\af_test> rustup default stable
info: using existing install for 'stable-x86_64-pc-windows-msvc'
info: default toolchain set to 'stable-x86_64-pc-windows-msvc'

  stable-x86_64-pc-windows-msvc unchanged - rustc 1.29.0 (aa3ca1994 2018-09-11)

PS C:\Users\gibsona\rust\af_test> cargo run
    Updating git repository `https://github.com/9prady9/arrayfire-rust`
   Compiling arrayfire v3.6.0 (https://github.com/9prady9/arrayfire-rust?branch=typed_arrays#4bba5caf)
   Compiling af_test v0.1.0 (file:///C:/Users/gibsona/rust/af_test)
    Finished dev [unoptimized + debuginfo] target(s) in 1m 17s
     Running `target\debug\af_test.exe`
Create a 8-by-8 matrix of random 32 bit floats on the OpenCL
dims = [8 8 1 1]
error: process didn't exit successfully: `target\debug\af_test.exe` (exit code: 3221225501)

**Comment by 9prady9** [comment] 2018-09-17 14:15
Thanks for trying it out. I will check both master and the PR on windows tomorrow and let you know how that goes for me.

**Comment by Aidan24** [comment] 2018-09-17 14:27
Thanks 9prady9, I really appreciate it. I am having the same issue on two different Windows machines which have different processors and different graphics cards (although they are both Nvidia).

**Comment by 9prady9** [comment] 2018-09-17 14:38
Well, I have a NVIDIA card myself. So, hopefully I will be able to reproduce it on my end as well.

**Comment by 9prady9** [comment] 2018-09-20 14:49
@Aidan24 Sorry about the delay, was busy with other tasks. I think I was able to reproduce this on Windows, interestingly this isn't happening on Linux, not sure about OSX. I am going to try using gnu-toolchain and see what happens with that toolchain.

**Comment by Aidan24** [comment] 2018-09-20 14:55
Hi 9prady9, I did try this with the gnu-toolchain on Windows using MinGW and got the same results as MSVC.

**Comment by 9prady9** [comment] 2018-09-20 15:00
Yeah, looks like it, for some weird reason my first run with gnu toolchain ran fine although from then on I got segfaults consistently.

**Comment by Aidan24** [comment] 2018-09-27 09:33
That's excellent news. Thanks for your help.

**Closed** 2018-09-27 13:05 UTC

**Comment by Aidan24** [comment] 2018-09-27 17:32
@9prady9 I'm still having problems with randu, I think I'm picking up the latest master branch, is there something else I need to do? Thanks

**Comment by Aidan24** [comment] 2018-09-27 17:38
With AF_PRINT_ERRORS = 1 I get:
In function af_err __cdecl af_randu(void **,const unsigned int,const __int64 *const ,const af_dtype)
In file src\api\c\random.cpp:324
Invalid type for argument 3

I think this is for the line 
let c = randu::<f64>(dims);

Maybe I'm doing something stupid...

**Comment by 9prady9** [comment] 2018-09-28 05:03
Shouldn't it be randu::<f32>() ? Where is the generic type ?

**Comment by 9prady9** [comment] 2018-09-28 05:14
Which version of the wrapper are you using?

**Comment by Aidan24** [comment] 2018-09-28 05:15
Sorry I had f64 in there but github formatted it out because I originally forgot to quote it as code and I guess it removes stuff in angled brackets

**Comment by 9prady9** [comment] 2018-09-28 05:33
@Aidan24 Did you change the version of rust wrapper crate to 3.6 ? Or if you are doing this `arrayfire = { git = "https://github.com/9prady9/arrayfire-rust", branch = "master" }`, may be you should do cargo update ?

**Comment by Aidan24** [comment] 2018-09-28 06:11
I'm using arrayfire = { git = "https://github.com/9prady9/arrayfire-rust", branch = "master" }. I have done cargo update, but no dice. I can create arrays from new, it seems to be just randu that fails

**Comment by 9prady9** [comment] 2018-09-28 06:34
My bad, can you change it to following
`https://github.com/arrayfire/arrayfire-rust`
instead of
`https://github.com/9prady9/arrayfire-rust`

I may not have updated master on my fork.

**Comment by Aidan24** [comment] 2018-09-28 06:58
That did it. Thank you so much.
