### ISSUE TITLE
Diferent results running the same code (without any randomness involved)

### ISSUE THREAD

**Issue by Tzeroxik** [arrayfire/arrayfire-rust#199] opened 2019-06-28 16:48 UTC
I'm using arrayfire in this project "https://github.com/fica-ps/fica" and running the test separate_functions on lib.rs ("cargo test separate_functions -- --nocapture").

The test is giving me diferent results on every other run. Which is strange since it has no random component. 

---
[2 2 1 1]
   -0.2660     0.9640 
    0.2064    -0.9785 
---
[2 2 1 1]
   -0.2660     0.9640 
   -0.8619     0.5071 
---

Is this expected because of sync or something else?

arrayfire-rust version: 3.6.1
arrayfire: the latest binary instalation available on the website

**Comment by 9prady9** [comment] 2019-06-29 08:56
@Tzeroxik I have cloned your repository and tried the cargo test separate_functions command couple of times. In all the attempts, the following is the output of it.
```
Component 1 converged in 0 iterations with distance 0.0004889604418298887

[2 2 1 1]
   -0.2660     0.9640 
    0.5704     0.8214 

test tests::separate_functions ... ok

```

Perhaps, you can setup your project in a docker file and reproduce it and share that docker file here. I will try the docker file. We should be able to reliably reproduce it that way.

**Comment by Tzeroxik** [comment] 2019-06-29 09:17
@9prady9 okay I'll do it as soon as I can.

**Comment by Tzeroxik** [comment] 2019-06-29 15:04
Sorry I couldn't send the docker file yet, but I had a colleague run some tests and he found out that only backend where it happens is the CPU.

**Comment by 9prady9** [comment] 2019-06-29 15:39
It is odd that only CPU backend is giving incorrect result. I could reproduce the random output while running CPU backend. I was letting it choose the backend earlier when it used CUDA backend, hence I wasn't seeing the issue.

I will check your project code to understand what functions are being called.

**Comment by Tzeroxik** [comment] 2019-06-29 15:42
Thank you, we'll keep trying to figure it out on our end too, and await to hear from you.

**Comment by 9prady9** [comment] 2019-07-08 05:24
@Tzeroxik Sorry about the delay, I was busy with some personal work last week. Did you find anything on your end ? Can you also please tell me from which version you found this behavior ?

**Comment by 9prady9** [comment] 2019-07-08 07:16
It seems like fica_impl is using quite a few arrayfire functions (of course no random number generation related). Have you tried finding out where the outcome is deviating on each iteration ? I have tried with `max_iter=2`  and the variable `nw` inside `fica_impl` `max_iter` loop seems to be producing some `NaN` values in `nw` matrix (irrespective of the backend in usage). Have you looked into that ?

**Comment by Tzeroxik** [comment] 2019-07-08 12:56
I was using arrayfire-rust 3.6.1, and didn't have any NaN values, still couldn't find the cause.
Sadly we have been forced to switch to another library because of the project deadline.

**Comment by 9prady9** [comment] 2019-07-08 13:02
Sad to hear that! I will keep the issue open and update here once I find something.

**Comment by Tzeroxik** [comment] 2019-07-08 13:08
Thank you, best of lucks! Hopefuly this can be resolved soon as i'd love to use this in future projects. 
I'll sure try to find out more about it when I'm free.

**Comment by 9prady9** [comment] 2019-11-19 12:50
@Tzeroxik It seems fica code moved away from rust code base altogether. Is that correct ? I am unable to the find the old code in git history as well.

If it is possible, please send me an archived version of your rust code base so that I can try reproducing it on my end.

**Comment by Tzeroxik** [comment] 2019-11-24 20:01
Hello, sorry for taking so long to respond, here's the latest archived version we have:

[oldfica.zip](https://github.com/arrayfire/arrayfire-rust/files/3884064/oldfica.zip)

**Comment by 9prady9** [comment] 2019-11-26 01:53
@Tzeroxik Thank you for the archived code, I will look into it.

**Comment by 9prady9** [comment] 2019-11-26 13:06
I found the problem - it is the call sites where `Matrix::new_empty` is being used. The arrays/matrices created using this call are usually created as mutable variables, however they are being passed around as non-mutable references even before any data is populated into the memory allocated for those arrays. I have verified this from one of the variables `ret_weights` which is created from `Matrix::new_empty` call in the function `fast_ica_impl` inside `src/fastica.rs` file. CUDA/OpenCL doesn't seem to differ in the outcome only by chance since most doubles are initialized to `0.0` but that is not a guarantee of any sort. Hence, you were noticing some differences in CPU backend where this default value assumption is being broken.

When I replaced `Matrix::new_empty` call with `constant(0.0f64, ...)` in the line I mentioned above, the difference in results at that stage of code path disappeared. There are more locations where this is happening, for example in `decorrelate` function. Once all these call sites are fixed, this issue should go away.

In a single line, it is the issue of using uninitialized values. I am closing the issue as it isn't a bug in upstream library or the rust wrapper. Feel free to reopen if you find any contradicting evidence later.

I see that you have switched to C++ code base on your main repository now, have you tried using our C++ API directly ? It is not as verbose as rust wrapper for sure.

**Closed by 9prady9** 2019-11-26 13:06 UTC

**Comment by Tzeroxik** [comment] 2019-11-30 02:17
I see, we didn't try the C++ backend because of some requirements in favor of Eigen (not having additional runtime was a plus in this situation). But that's good to know, I'll surely use this on other projects. I do prefer Rustb to C++, even if it's a bit more verbose. Cheers on the good work!
