### ISSUE TITLE
Problem compiling simple example

### ISSUE THREAD

**Issue by botev** [arrayfire/arrayfire-rust#101] opened 2017-02-10 01:45 UTC
I have set up `AF_PATH=/opt/common/arrayfire-3` which is the install directory. 
However, trying to run the simple example from the repository I get:
```
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/home/alex/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/media/hdd/work/rust/gir/target/debug/deps/test-5e38923b8801a2b7.0.o" "-o" "/media/hdd/work/rust/gir/target/debug/deps/test-5e38923b8801a2b7" "-Wl,--gc-sections" "-pie" "-nodefaultlibs" "-L" "/media/hdd/work/rust/gir/target/debug/deps" "-L" "/media/hdd/work/rust/gir/target/debug/build/backtrace-sys-c5e6113905bd3f96/out/.libs" "-L" "/opt/common/arrayfire-3/lib" "-L" "/home/alex/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "-Wl,-Bdynamic" "/media/hdd/work/rust/gir/target/debug/deps/libgir-2392f3d7a7713b26.rlib" "/media/hdd/work/rust/gir/target/debug/deps/libocl-ad03f7af061a5bf3.rlib" "/media/hdd/work/rust/gir/target/debug/deps/libarrayfire-469f74c2e2fcb8b2.rlib" "/media/hdd/work/rust/gir/target/debug/deps/libslog_term-7bf030caf0f7defe.rlib" "/media/hdd/work/rust/gir/target/debug/deps/libslog_stream-173624b318b06bc5.rlib" "/media/hdd/work/rust/gir/target/debug/deps/libslog_extra-2412627c39dd57bf.rlib" "/media/hdd/work/rust/gir/target/debug/deps/libtera-71b3cb772a3143dc.rlib" "/media/hdd/work/rust/gir/target/debug/deps/libchrono-7f6de010bb6656a2.rlib" "/media/hdd/work/rust/gir/target/debug/deps/libtime-cd5e3a346d1a17b6.rlib" "/media/hdd/work/rust/gir/target/debug/deps/libhumansize-b8854c23c33aea86.rlib" "/media/hdd/work/rust/gir/target/debug/deps/liblazy_static-2a16fcec40d2bdf3.rlib" "/media/hdd/work/rust/gir/target/debug/deps/libslug-f4ee6db63b519e8b.rlib" "/media/hdd/work/rust/gir/target/debug/deps/libunidecode-98164bdaaf2e94ff.rlib" "/media/hdd/work/rust/gir/target/debug/deps/libserde_json-da7c1c3bec2b9304.rlib" "/media/hdd/work/rust/gir/target/debug/deps/libserde-13ca9a5f25ca5eb7.rlib" "/media/hdd/work/rust/gir/target/debug/deps/libpest-c39f935a46accd8a.rlib" "/media/hdd/work/rust/gir/target/debug/deps/libslog-444150cc9f588741.rlib" "/media/hdd/work/rust/gir/target/debug/deps/libisatty-02586bf5f6f35699.rlib" "/media/hdd/work/rust/gir/target/debug/deps/libglob-448fa4fbc5ac9e4c.rlib" "/media/hdd/work/rust/gir/target/debug/deps/libdtoa-800e947d6adc2627.rlib" "/media/hdd/work/rust/gir/target/debug/deps/libocl_core-cc200e0a441a12c1.rlib" "/media/hdd/work/rust/gir/target/debug/deps/libcl_sys-ded1ce1e2552cbec.rlib" "/media/hdd/work/rust/gir/target/debug/deps/libenum_primitive-b8ff90d65ad8e4c3.rlib" "/media/hdd/work/rust/gir/target/debug/deps/libbitflags-8510a47beebe00a6.rlib" "/media/hdd/work/rust/gir/target/debug/deps/libsymbolic_polynomials-7220693cdb79348f.rlib" "/media/hdd/work/rust/gir/target/debug/deps/libserde-eb150695fea2362e.rlib" "/media/hdd/work/rust/gir/target/debug/deps/libnum-4f5490b7b4313ad0.rlib" "/media/hdd/work/rust/gir/target/debug/deps/libnum_rational-e1a0d96e4c2f73b6.rlib" "/media/hdd/work/rust/gir/target/debug/deps/libnum_bigint-a0b0a32a0399692f.rlib" "/media/hdd/work/rust/gir/target/debug/deps/librand-c9d9fbdab2355ee4.rlib" "/media/hdd/work/rust/gir/target/debug/deps/libnum_complex-2d6fd57f39d31306.rlib" "/media/hdd/work/rust/gir/target/debug/deps/libnum_iter-a1bfa3b9618fdfe0.rlib" "/media/hdd/work/rust/gir/target/debug/deps/libnum_integer-f617fb54b59f25d7.rlib" "/media/hdd/work/rust/gir/target/debug/deps/libnum_traits-51f88ce8f32c0283.rlib" "/media/hdd/work/rust/gir/target/debug/deps/librustc_serialize-2c0b16b7ceb9fdcb.rlib" "/media/hdd/work/rust/gir/target/debug/deps/liberror_chain-51998ce5824b8fe7.rlib" "/media/hdd/work/rust/gir/target/debug/deps/libbacktrace-4bd69dcf892822ef.rlib" "/media/hdd/work/rust/gir/target/debug/deps/libbacktrace_sys-0fb10b5551dddae6.rlib" "/media/hdd/work/rust/gir/target/debug/deps/libcfg_if-5cf5b4dd25466da1.rlib" "/media/hdd/work/rust/gir/target/debug/deps/libdbghelp-80abcaa2ef08d9db.rlib" "/media/hdd/work/rust/gir/target/debug/deps/libwinapi-a5898d7aceb63fac.rlib" "/media/hdd/work/rust/gir/target/debug/deps/libkernel32-835ed4d4f4dc2d3e.rlib" "/media/hdd/work/rust/gir/target/debug/deps/librustc_demangle-ffe0cd46130fc1c4.rlib" "/media/hdd/work/rust/gir/target/debug/deps/libthread_local-a561abce7ea185f1.rlib" "/media/hdd/work/rust/gir/target/debug/deps/libthread_id-e41c347f28e6505f.rlib" "/media/hdd/work/rust/gir/target/debug/deps/libitoa-f4899e2d13429285.rlib" "/media/hdd/work/rust/gir/target/debug/deps/libregex-59ef72234132697a.rlib" "/media/hdd/work/rust/gir/target/debug/deps/libutf8_ranges-96b53fb879382c48.rlib" "/media/hdd/work/rust/gir/target/debug/deps/libregex_syntax-21fcdc3a2a66b202.rlib" "/media/hdd/work/rust/gir/target/debug/deps/libthread_local-0387953ee07a9f1b.rlib" "/media/hdd/work/rust/gir/target/debug/deps/libunreachable-ebcc746f6a526ccc.rlib" "/media/hdd/work/rust/gir/target/debug/deps/libvoid-408bd2d66dde02c1.rlib" "/media/hdd/work/rust/gir/target/debug/deps/libthread_id-7c664cbece6d9f97.rlib" "/media/hdd/work/rust/gir/target/debug/deps/libaho_corasick-74441b4f7f334b84.rlib" "/media/hdd/work/rust/gir/target/debug/deps/libmemchr-2d0f309229d6f8c6.rlib" "/media/hdd/work/rust/gir/target/debug/deps/liblibc-2a4507ee5e52ea3e.rlib" "/media/hdd/work/rust/gir/target/debug/deps/liburl-aa3392667e4f87a3.rlib" "/media/hdd/work/rust/gir/target/debug/deps/libidna-3bab7d99255950c3.rlib" "/media/hdd/work/rust/gir/target/debug/deps/libunicode_normalization-0297b14f098a4d93.rlib" "/media/hdd/work/rust/gir/target/debug/deps/libunicode_bidi-40fd65c5b5d04ab6.rlib" "/media/hdd/work/rust/gir/target/debug/deps/libmatches-8f1598a59712d6cc.rlib" "/home/alex/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-93390f7535a2b2f7.rlib" "/home/alex/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-277781e5e83f4ddf.rlib" "/home/alex/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-9fb0680200b1f1d7.rlib" "/home/alex/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librand-8fe8e03da90d4fd4.rlib" "/home/alex/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcollections-91e6e43d741825a3.rlib" "/home/alex/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-91c6f0edecc68d05.rlib" "/home/alex/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_jemalloc-3e3384d4e8c6562d.rlib" "/home/alex/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-552ce29795ce9c9d.rlib" "/home/alex/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_unicode-e19b6c0e5bf50406.rlib" "/home/alex/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-c1ab5423a7223378.rlib" "/home/alex/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-5d4fca8590bb0079.rlib" "-l" "OpenCL" "-l" "OpenCL" "-l" "util" "-l" "dl" "-l" "rt" "-l" "pthread" "-l" "gcc_s" "-l" "pthread" "-l" "c" "-l" "m" "-l" "rt" "-l" "util"
  = note: /media/hdd/work/rust/gir/target/debug/deps/test-5e38923b8801a2b7.0.o: In function `arrayfire::index::{{impl}}::set<u32>':
          /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/arrayfire-3.4.1/src/index.rs:66: undefined reference to `af_set_seq_indexer'
          /media/hdd/work/rust/gir/target/debug/deps/test-5e38923b8801a2b7.0.o: In function `arrayfire::array::{{impl}}::new<i32>':
          /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/arrayfire-3.4.1/src/array.rs:149: undefined reference to `af_create_array'
          /media/hdd/work/rust/gir/target/debug/deps/test-5e38923b8801a2b7.0.o: In function `arrayfire::array::{{impl}}::new<f32>':
          /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/arrayfire-3.4.1/src/array.rs:149: undefined reference to `af_create_array'
          /media/hdd/work/rust/gir/target/debug/deps/test-5e38923b8801a2b7.0.o: In function `arrayfire::index::index<u32>':
          /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/arrayfire-3.4.1/src/index.rs:136: undefined reference to `af_index'
          /media/hdd/work/rust/gir/target/debug/deps/test-5e38923b8801a2b7.0.o: In function `arrayfire::random::randu<f32>':
          /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/arrayfire-3.4.1/src/random/mod.rs:88: undefined reference to `af_randu'
          /media/hdd/work/rust/gir/target/debug/deps/libarrayfire-469f74c2e2fcb8b2.rlib(arrayfire-469f74c2e2fcb8b2.0.o): In function `arrayfire::array::{{impl}}::dims':
          /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/arrayfire-3.4.1/src/array.rs:241: undefined reference to `af_get_dims'
          /media/hdd/work/rust/gir/target/debug/deps/libarrayfire-469f74c2e2fcb8b2.rlib(arrayfire-469f74c2e2fcb8b2.0.o): In function `arrayfire::array::{{impl}}::clone':
          /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/arrayfire-3.4.1/src/array.rs:399: undefined reference to `af_retain_array'
          /media/hdd/work/rust/gir/target/debug/deps/libarrayfire-469f74c2e2fcb8b2.rlib(arrayfire-469f74c2e2fcb8b2.0.o): In function `arrayfire::array::{{impl}}::drop':
          /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/arrayfire-3.4.1/src/array.rs:412: undefined reference to `af_release_array'
          /media/hdd/work/rust/gir/target/debug/deps/libarrayfire-469f74c2e2fcb8b2.rlib(arrayfire-469f74c2e2fcb8b2.0.o): In function `arrayfire::array::print':
          /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/arrayfire-3.4.1/src/array.rs:450: undefined reference to `af_print_array_gen'
          /media/hdd/work/rust/gir/target/debug/deps/libarrayfire-469f74c2e2fcb8b2.rlib(arrayfire-469f74c2e2fcb8b2.0.o): In function `arrayfire::array::print_gen':
          /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/arrayfire-3.4.1/src/array.rs:491: undefined reference to `af_print_array_gen'
          /media/hdd/work/rust/gir/target/debug/deps/libarrayfire-469f74c2e2fcb8b2.rlib(arrayfire-469f74c2e2fcb8b2.0.o): In function `arrayfire::algorithm::sort_index':
          /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/arrayfire-3.4.1/src/algorithm/mod.rs:768: undefined reference to `af_sort_index'
          /media/hdd/work/rust/gir/target/debug/deps/libarrayfire-469f74c2e2fcb8b2.rlib(arrayfire-469f74c2e2fcb8b2.0.o): In function `arrayfire::arith::{{impl}}::not':
          /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/arrayfire-3.4.1/src/arith/mod.rs:111: undefined reference to `af_not'
          /media/hdd/work/rust/gir/target/debug/deps/libarrayfire-469f74c2e2fcb8b2.rlib(arrayfire-469f74c2e2fcb8b2.0.o): In function `arrayfire::device::info':
          /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/arrayfire-3.4.1/src/device/mod.rs:54: undefined reference to `af_info'
          /media/hdd/work/rust/gir/target/debug/deps/libarrayfire-469f74c2e2fcb8b2.rlib(arrayfire-469f74c2e2fcb8b2.0.o): In function `arrayfire::device::set_device':
          /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/arrayfire-3.4.1/src/device/mod.rs:105: undefined reference to `af_set_device'
          /media/hdd/work/rust/gir/target/debug/deps/libarrayfire-469f74c2e2fcb8b2.rlib(arrayfire-469f74c2e2fcb8b2.0.o): In function `arrayfire::index::{{impl}}::set':
          /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/arrayfire-3.4.1/src/index.rs:51: undefined reference to `af_set_array_indexer'
          /media/hdd/work/rust/gir/target/debug/deps/libarrayfire-469f74c2e2fcb8b2.rlib(arrayfire-469f74c2e2fcb8b2.0.o): In function `arrayfire::index::{{impl}}::new':
          /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/arrayfire-3.4.1/src/index.rs:79: undefined reference to `af_create_indexers'
          /media/hdd/work/rust/gir/target/debug/deps/libarrayfire-469f74c2e2fcb8b2.rlib(arrayfire-469f74c2e2fcb8b2.0.o): In function `arrayfire::index::{{impl}}::drop':
          /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/arrayfire-3.4.1/src/index.rs:107: undefined reference to `af_release_indexers'
          /media/hdd/work/rust/gir/target/debug/deps/libarrayfire-469f74c2e2fcb8b2.rlib(arrayfire-469f74c2e2fcb8b2.0.o): In function `arrayfire::index::index<f64>':
          /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/arrayfire-3.4.1/src/index.rs:136: undefined reference to `af_index'
          /media/hdd/work/rust/gir/target/debug/deps/libarrayfire-469f74c2e2fcb8b2.rlib(arrayfire-469f74c2e2fcb8b2.0.o): In function `arrayfire::index::assign_seq<f64>':
          /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/arrayfire-3.4.1/src/index.rs:304: undefined reference to `af_assign_seq'
          /media/hdd/work/rust/gir/target/debug/deps/libarrayfire-469f74c2e2fcb8b2.rlib(arrayfire-469f74c2e2fcb8b2.0.o): In function `arrayfire::index::index_gen':
          /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/arrayfire-3.4.1/src/index.rs:344: undefined reference to `af_index_gen'
          /media/hdd/work/rust/gir/target/debug/deps/libarrayfire-469f74c2e2fcb8b2.rlib(arrayfire-469f74c2e2fcb8b2.0.o): In function `arrayfire::signal::fft':
          /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/arrayfire-3.4.1/src/signal/mod.rs:149: undefined reference to `af_fft'
          /media/hdd/work/rust/gir/target/debug/deps/libarrayfire-469f74c2e2fcb8b2.rlib(arrayfire-469f74c2e2fcb8b2.0.o): In function `arrayfire::array::{{impl}}::is_scalar':
          /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/arrayfire-3.4.1/src/array.rs:318: undefined reference to `af_is_scalar'
          /media/hdd/work/rust/gir/target/debug/deps/libarrayfire-469f74c2e2fcb8b2.rlib(arrayfire-469f74c2e2fcb8b2.0.o): In function `arrayfire::array::{{impl}}::is_single':
          /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/arrayfire-3.4.1/src/array.rs:324: undefined reference to `af_is_single'
          /media/hdd/work/rust/gir/target/debug/deps/libarrayfire-469f74c2e2fcb8b2.rlib(arrayfire-469f74c2e2fcb8b2.0.o): In function `arrayfire::arith::sin':
          /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/arrayfire-3.4.1/src/arith/mod.rs:142: undefined reference to `af_sin'
          /media/hdd/work/rust/gir/target/debug/deps/libarrayfire-469f74c2e2fcb8b2.rlib(arrayfire-469f74c2e2fcb8b2.0.o): In function `arrayfire::arith::cos':
          /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/arrayfire-3.4.1/src/arith/mod.rs:143: undefined reference to `af_cos'
          /media/hdd/work/rust/gir/target/debug/deps/libarrayfire-469f74c2e2fcb8b2.rlib(arrayfire-469f74c2e2fcb8b2.0.o): In function `arrayfire::arith::add_helper':
          /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/arrayfire-3.4.1/src/arith/mod.rs:287: undefined reference to `af_add'
          /media/hdd/work/rust/gir/target/debug/deps/libarrayfire-469f74c2e2fcb8b2.rlib(arrayfire-469f74c2e2fcb8b2.0.o): In function `arrayfire::arith::{{impl}}::add':
          /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/arrayfire-3.4.1/src/arith/mod.rs:423: undefined reference to `af_add'
          /media/hdd/work/rust/gir/target/debug/deps/libarrayfire-469f74c2e2fcb8b2.rlib(arrayfire-469f74c2e2fcb8b2.0.o): In function `arrayfire::data::{{impl}}::generate':
          /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/arrayfire-3.4.1/src/data/mod.rs:159: undefined reference to `af_constant'
          /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/arrayfire-3.4.1/src/data/mod.rs:163: undefined reference to `af_constant'
          /media/hdd/work/rust/gir/target/debug/deps/libarrayfire-469f74c2e2fcb8b2.rlib(arrayfire-469f74c2e2fcb8b2.0.o): In function `arrayfire::data::tile':
          /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/arrayfire-3.4.1/src/data/mod.rs:384: undefined reference to `af_tile'
          collect2: error: ld returned 1 exit status
```
I think something is failing on the linking, but I can not say what and I'm not sure what needs changing in Rust.

**Comment by 9prady9** [comment] 2017-02-10 04:59
Did you do `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$AF_PATH/lib` ?

**Comment by botev** [comment] 2017-02-10 11:58
Yes that is exported in the standard environment as I'm using Arrayfire on my C++ projects, where it works fine.

**Comment by 9prady9** [comment] 2017-02-10 12:09
I haven't been able to reproduce this on my end using rust's stable channel. Can you clone arrayfire-rust from github and see if you can run any examples after setting the PATHSs ?

**Comment by botev** [comment] 2017-02-10 14:50
Ok, so it was my mistake all along. Since I'm working on like 4 clusters and 3 machines on my laptop apparently the correct path was `/opt/arrayfire-3` without the `common`, so doing this correctly fixed it. 
I guess for anyone encountering this double check the `AF_PATH` variable.

**Comment by 9prady9** [comment] 2017-02-10 14:51
Closing the issue in that case.

**Closed by 9prady9** 2017-02-10 14:51 UTC

**Comment by botev** [comment] 2017-02-11 14:52
So something else weird is happening. So if from the example I comment out all of the printing I got an exit status `1`. E.g. the program:
```
af::set_device(0);
    af::info();

    let num_rows: u64 = 5;
    let num_cols: u64 = 3;
    let values: [f32; 3] = [1.0, 2.0, 3.0];
    let indices = af::Array::new(&values, af::Dim4::new(&[3, 1, 1, 1]));

    let dims = af::Dim4::new(&[num_rows, num_cols, 1, 1]);

    let a = af::randu::<f32>(dims);
```
Produces exit status `1`. If we add at the end the line
```
af_print!("Create a 5-by-3 matrix of random floats on the GPU", a);
```
It works fine. Is this something that can be avoided, for instance when I just want to fetch and display the information about arrayfire without printing any matrices.

**Comment by 9prady9** [comment] 2017-02-12 05:20
@botev Unfortunately, i am unable replicate the problem you are experiencing. Can you please show me the output of `af::info` call.

**Comment by botev** [comment] 2017-02-12 11:42
Hmm that is very weird, I will try this on a second machine tomorrow as well. So when I have the print statement the output looks like:
```
ArrayFire v3.4.1 (OpenCL, 64-bit Linux, build b9055b1)
[0] INTEL   : Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz, 7674 MB
-1- Experimental OpenCL 2.1 CPU Only Platform: Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz, 7674 MB
```

**Comment by botev** [comment] 2017-02-12 21:46
I've tried it on a separate machine and that does not happen. Would you by any chance have any idea of how to debug this (or anything worth looking into)? I will also post this on the rust general forum if anyone has any idea. 

I'm running this on a lenovo laptop with ubuntu:
Linux botev-ThinkPad-T440 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by botev** [comment] 2017-02-13 00:30
I've ran `valgrind --tool=memcheck --leak-check=full --leak-check=full --show-leak-kinds=all --track-origins=yes` on the whole program and got this back:
```
==23369== Process terminating with default action of signal 11 (SIGSEGV)
==23369==  Access not within mapped region at address 0x4027138
==23369==    at 0x1D51F970: ??? (in /opt/intel/intel-opencl-1.2-5.0.0.43/opencl-1.2-5.0.0.43/lib64/libOclCpuBackEnd.so)
==23369==    by 0x1D520F3B: ??? (in /opt/intel/intel-opencl-1.2-5.0.0.43/opencl-1.2-5.0.0.43/lib64/libOclCpuBackEnd.so)
==23369==    by 0x1CF810F4: ??? (in /opt/intel/intel-opencl-1.2-6.3.0.1904/opencl-1.2-sdk-6.3.0.1904/opencl-2.1-exp/lib64/libcpu_device_2_1.so)
==23369==    by 0x1CF81188: ??? (in /opt/intel/intel-opencl-1.2-6.3.0.1904/opencl-1.2-sdk-6.3.0.1904/opencl-2.1-exp/lib64/libcpu_device_2_1.so)
==23369==    by 0x1CF85F99: ??? (in /opt/intel/intel-opencl-1.2-6.3.0.1904/opencl-1.2-sdk-6.3.0.1904/opencl-2.1-exp/lib64/libcpu_device_2_1.so)
==23369==    by 0x1C874DDF: ??? (in /opt/intel/intel-opencl-1.2-6.3.0.1904/opencl-1.2-sdk-6.3.0.1904/opencl-2.1-exp/lib64/libintelocl_2_1.so)
==23369==    by 0x1C82A4E7: ??? (in /opt/intel/intel-opencl-1.2-6.3.0.1904/opencl-1.2-sdk-6.3.0.1904/opencl-2.1-exp/lib64/libintelocl_2_1.so)
==23369==    by 0x1C81300A: ??? (in /opt/intel/intel-opencl-1.2-6.3.0.1904/opencl-1.2-sdk-6.3.0.1904/opencl-2.1-exp/lib64/libintelocl_2_1.so)
==23369==    by 0x1C7DCBF9: clReleaseContext (in /opt/intel/intel-opencl-1.2-6.3.0.1904/opencl-1.2-sdk-6.3.0.1904/opencl-2.1-exp/lib64/libintelocl_2_1.so)
==23369==    by 0x123AEF7D: release (cl2.hpp:1523)
==23369==    by 0x123AEF7D: release (cl2.hpp:1722)
==23369==    by 0x123AEF7D: ~Wrapper (cl2.hpp:1654)
==23369==    by 0x123AEF7D: ~Context (cl2.hpp:2571)
==23369==    by 0x123AEF7D: opencl::DeviceManager::~DeviceManager() (platform.cpp:102)
==23369==    by 0x5B2C258: __run_exit_handlers (exit.c:82)
==23369==    by 0x5B2C2A4: exit (exit.c:104)
```
The full output of valgrind is here: http://www.filedropper.com/check_2. 

I've repeated this with the CPU backend and that works fine. This probably concludes that the OpenCL I've downloaded and installed from Intel is what is causing the issue, rather than arrayfire. I did that mainly cause I needed opencl 2. Again this seems not to be arrayfire issue, but would you have any suggestions on which OpenCL to get?

**Comment by 9prady9** [comment] 2017-02-13 06:43
I am afraid there isn't much we can do on the user program or library side if the problem is stemming from the Intel driver. You can try an older version of driver and see if that changes any thing.

**Comment by pavanky** [comment] 2017-02-13 06:46
@botev There are two versions of intel-opencl installed on the system. This may be the root cause of the issue. A library in 1.2-6.3 is picking a library frm 1.2-5.0. Try deleting 1.2-5 and see if it works.

**Comment by botev** [comment] 2017-02-13 09:24
@pavanky Good catch that fixed it all.
