### ISSUE TITLE
0 backends in Rust 

### ISSUE THREAD

**Issue by jamcar23** [arrayfire/arrayfire-rust#86] opened 2016-09-20 16:57 UTC
Hey everyone, 

I'm on OSX 10.10 and I built and installed ArrayFire C++ with the CPU and OpenCL backend. I've ran the C++ tests (everything passed), ran the basic_unified.cpp example from /tmp, and used this in other C++ projects so I know the C++ version works.  

I downloaded the AF Rust repo, initiated the submodules, compiled the project without issues, and set the `AF_PATH`. However when I run `cargo run --example unified`  I get 
`There are 0 available backends`

I also tried using the AF Rust from crates.io and I get the same thing. Any ideas why this is happening?

P.S. I'm using AF 3.4.0

**Comment by 9prady9** [comment] 2016-09-21 03:52
Can you please check the value of `LD_LIBRARY_PATH` and `DYLD_LIBRARY_PATH`, it should contain `$AF_PTH/lib`. Usually, 0 backends are found when any of dependency libraries is not available to load during the program run time.

Can you also paste the output of the following command here.
`cargo run --example unified --verbose`

**Comment by jamcar23** [comment] 2016-09-22 17:29
The output looks like this: 

```
Fresh semver v0.1.20
       Fresh num-traits v0.1.35
       Fresh lazy_static v0.2.1
       Fresh rustc-serialize v0.3.19
       Fresh libc v0.2.16
       Fresh rustc_version v0.1.7
       Fresh num-integer v0.1.32
       Fresh num-complex v0.1.35
       Fresh rand v0.3.14
       Fresh num-iter v0.1.32
       Fresh num-bigint v0.1.35
       Fresh num-rational v0.1.35
       Fresh num v0.1.35
       Fresh arrayfire v3.4.0 (file:///Users/jamescarroll/Documents/rust/arrayfire-rust)
     Running `target/debug/examples/unified`
There are 0 available backends
```

The paths are set correctly in ```LD_LIBRARY_PATH``` and ```DYLD_LIBRARY_PATH```. Do I need  I need to link them in cargo?

**Comment by 9prady9** [comment] 2016-09-27 05:58
I can't think of a reason why C++ version of the example is working fine and the wrapper is not. The reason i say that is, unified API dynamically loads all the individual backend libraries of arrayfire and then calls the apparopriate backend function at run time. So, if unified API (`libaf.dylib`) is able to find all backends, then the rust wrapper shouldn't find any problem in doing the same.

I have requested one of my colleagues who uses OSX 10.10 to try and reproduce the problem. I shall update here as soon as i here from him.

**Comment by 9prady9** [comment] 2016-09-27 06:13
@jamcar23 On a unrelated topic, we have an issue reported for OSX [here](https://github.com/arrayfire/arrayfire-rust/issues/60) that says can't even run example for OpenCL backend for discrete GPU card. Can you please tell what devices does the OpenCL backend report for you in C++ example and does the example run for all reported devices ?

Thanks!

**Comment by jamcar23** [comment] 2016-09-27 13:43
@9prady9 I just ran the helloworld.cpp example with OpenCL on an integrated Intel Iris Pro and got this:

```
ArrayFire v3.4.0 (OpenCL, 64-bit Mac OSX, build 10d9716)
[0] APPLE   : Iris Pro, 1536 MB
Create a 5-by-3 matrix of random floats on the GPU
A
[5 3 1 1]
    0.3990     0.5160     0.8831 
    0.6720     0.3932     0.0621 
    0.5339     0.2706     0.7089 
    0.1386     0.9455     0.9434 
    0.7353     0.1587     0.1227 

Element-wise arithmetic
B
[5 3 1 1]
    1.8885     1.9934     2.2727 
    2.1226     1.8831     1.5621 
    2.0089     1.7674     2.1510 
    1.6381     2.3108     2.3096 
    2.1708     1.6580     1.6224 

Negate the first three elements of second column
B
[5 3 1 1]
    1.8885    -1.9934     2.2727 
    2.1226    -1.8831     1.5621 
    2.0089    -1.7674     2.1510 
    1.6381     2.3108     2.3096 
    2.1708     1.6580     1.6224 

Fourier transform the result
C
[5 3 1 1]
         (9.8289,0.0000)          (-1.6751,0.0000)          (9.9178,0.0000) 
         (0.2648,-0.1720)          (-2.5026,5.7649)          (-0.3519,0.1506) 
         (-0.4579,0.3809)          (-1.6434,-1.7971)          (1.0748,-0.1153) 
         (-0.4579,-0.3809)          (-1.6434,1.7971)          (1.0748,0.1153) 
         (0.2648,0.1720)          (-2.5026,-5.7649)          (-0.3519,-0.1506) 

Grab last row
c
[1 3 1 1]
         (0.2648,0.1720)          (-2.5026,-5.7649)          (-0.3519,-0.1506) 
Scan Test
r
[16 4 1 1]
    2.0000     2.0000     2.0000     2.0000 
    2.0000     2.0000     2.0000     2.0000 
    2.0000     2.0000     2.0000     2.0000 
    2.0000     2.0000     2.0000     2.0000 
    2.0000     2.0000     2.0000     2.0000 
    2.0000     2.0000     2.0000     2.0000 
    2.0000     2.0000     2.0000     2.0000 
    2.0000     2.0000     2.0000     2.0000 
    2.0000     2.0000     2.0000     2.0000 
    2.0000     2.0000     2.0000     2.0000 
    2.0000     2.0000     2.0000     2.0000 
    2.0000     2.0000     2.0000     2.0000 
    2.0000     2.0000     2.0000     2.0000 
    2.0000     2.0000     2.0000     2.0000 
    2.0000     2.0000     2.0000     2.0000 
    2.0000     2.0000     2.0000     2.0000 

Scan
S
[16 4 1 1]
    2.0000     2.0000     2.0000     2.0000 
    4.0000     4.0000     4.0000     4.0000 
    8.0000     8.0000     8.0000     8.0000 
   16.0000    16.0000    16.0000    16.0000 
   32.0000    32.0000    32.0000    32.0000 
   64.0000    64.0000    64.0000    64.0000 
  128.0000   128.0000   128.0000   128.0000 
  256.0000   256.0000   256.0000   256.0000 
  512.0000   512.0000   512.0000   512.0000 
 1024.0000  1024.0000  1024.0000  1024.0000 
 2048.0000  2048.0000  2048.0000  2048.0000 
 4096.0000  4096.0000  4096.0000  4096.0000 
 8192.0000  8192.0000  8192.0000  8192.0000 
16384.0000 16384.0000 16384.0000 16384.0000 
32768.0000 32768.0000 32768.0000 32768.0000 
65536.0000 65536.0000 65536.0000 65536.0000 

Create 2-by-3 matrix from host data
D
[2 3 1 1]
    1.0000     3.0000     5.0000 
    2.0000     4.0000     6.0000 

Copy last column onto first
D
[2 3 1 1]
    5.0000     3.0000     5.0000 
    6.0000     4.0000     6.0000 

Sort A and print sorted array and corresponding indices
vals
[5 3 1 1]
    0.1386     0.1587     0.0621 
    0.3990     0.2706     0.1227 
    0.5339     0.3932     0.7089 
    0.6720     0.5160     0.8831 
    0.7353     0.9455     0.9434 

inds
[5 3 1 1]
         3          4          1 
         0          2          4 
         2          1          2 
         1          0          0 
         4          3          3 

```

**Comment by 9prady9** [comment] 2016-09-27 13:50
@jamcar23 thanks.

**Comment by jramapuram** [comment] 2016-10-22 00:41
@jamcar23 : opencl blows up when using the nvidia card. Do you have a mac with an ATI card?

**Comment by 9prady9** [comment] 2016-12-18 05:16
Closing the issue in favour of #60 which is the root cause of the problem. Please follow the progress in that issue.

**Closed by 9prady9** 2016-12-18 05:16 UTC
