### ISSUE TITLE
Can't manually drop array ?

### ISSUE THREAD

**Issue by BA8F0D39** [arrayfire/arrayfire-rust#286] opened 2021-03-14 04:53 UTC
Description
===========
Calling drop doesn't free the array from GPU's memory.
The array is still allocated in the GPU's memory.

ArrayFire v3.8.0 (CUDA, 64-bit Linux, build d86edd18)
Platform: CUDA Runtime 11.2, Driver: 460.32.03
[0] GeForce RTX 3090, 24267 MB, CUDA Compute 8.6
Info String:
ArrayFire v3.8.0 (CUDA, 64-bit Linux, build d86edd18)
Platform: CUDA Runtime 11.2, Driver: 460.32.03
[0] GeForce RTX 3090, 24267 MB, CUDA Compute 8.6
Arrayfire version: (3, 8, 0)
Name: GeForce_RTX_3090
Platform: CUDA
Toolkit: v11.2
Compute: 8.6
Revision: d86edd18

```
	use std::{thread, time};
	let arr_dims = arrayfire::Dim4::new(&[40000,40000,1,1]);
	let mut arr = arrayfire::randu::<f64>(arr_dims);

	let seconds = time::Duration::from_millis(10000);
	
	thread::sleep(seconds);


	arrayfire::sync(device);
	drop(arr);
	arrayfire::sync(device);
	println!("drop");


	let seconds = time::Duration::from_millis(10000);
	thread::sleep(seconds);

	println!("test");
```

**Comment by 9prady9** [comment] 2021-03-15 07:27
If you wanna force memory release, you can request the same using the `device_gc` but that is not going to result in optimized performance using ArrayFire.

**Comment by BA8F0D39** [comment] 2021-03-15 22:16
Size of arr1 is 14 GB
Size of arr2 is 3.2 GB 

After arr1 is initialized, total memory allocation on nvidia-smi is 14 GB.
After arr1 is dropped, total memory allocation on nvidia-smi is 14 GB.
When arr2 is initialized after arr1 is dropped, total memory allocation on nvidia-smi is 17.2 GB.
Total memory allocation stays at 17.2 GB until the end of the program.


```

	use std::{thread, time};
	let arr1_dims = arrayfire::Dim4::new(&[40000,40000,1,1]);
	let mut arr1 = arrayfire::randu::<f64>(arr1_dims);
	arrayfire::sync(device);
	println!("allocate arr1");

	let seconds = time::Duration::from_millis(10000);
	
	thread::sleep(seconds);


	arrayfire::sync(device);
	drop(arr1);
	arrayfire::sync(device);
	println!("drop");

	let arr2_dims = arrayfire::Dim4::new(&[10000,40000,1,1]);
	let mut arr2 = arrayfire::randu::<f64>(arr2_dims);

	arrayfire::sync(device);
	println!("allocate arr 2");


	let seconds = time::Duration::from_millis(10000);
	thread::sleep(seconds);

	println!("test");

```

After arr1 is dropped, why doesn't arr2 reuse the memory allocated by arr1?


Why doesn't arrayfire automatically call the garbage collection after dropping?

**Comment by 9prady9** [comment] 2021-03-16 04:32
> Why doesn't arrayfire automatically call the garbage collection after dropping?

Garbage collection (a.k.a calling `device_gc`) is a relatively expensive process as the memory manager has to go through the pool of allocations that it is book-keeping by calling free on those. Apart from that, `cudaFree` is synchronous call and ArrayFire's API is asychronous by design with few unavoidable exceptions. Even single `cudaFree` call is relatively expensive than marking the allocation for reuse which benefits majority of algorithms. In the event that, a user's use case cannot take advantage of the default memory manager behavior, we do allow them to override the default memory manager and writing their custom logic but I think this feature is not yet exposed via rust wrapper, it is only available in C++ wrapper as of now. I can look into this if you are interested in this approach. It's just that, we haven't had any custom memory manager use cases that came to our knowledge and thus I didn't make exposing that API a top priority at the moment.

Note we do automatically trigger GC when JIT node's memory pressure increases beyond certain limit. We cannot do the same with regular non-JIT allocations as the library cannot assume/estimate when it is right to call garbage collection as each user's algorithmic use case has varied requirements.

**Comment by BA8F0D39** [comment] 2021-03-16 20:18
Nvidia Jetson CPU/GPU unified memory might have trouble with arrayfire's memory management because it might duplicate memory in the shared RAM and there isn't any zero copy API calls between CPU and GPU.

Is there an API call to set unified memory across CPU/GPU for nvidia jetson?

**Comment by 9prady9** [comment] 2021-03-17 10:36
ArrayFire doesn't employ unified memory yet. We have some open requests regarding the same on upstream project.

- https://github.com/arrayfire/arrayfire/issues/363
- https://github.com/arrayfire/arrayfire/issues/1537

If the original question is addressed, please close this issue as this is a wrapper to ArrayFire and the concerned feature requests are already open in the upstream project. You can also post any questions or suggestions regarding this feature in the issue 363

**Closed** 2021-03-22 00:55 UTC
Labels: Question
