### ISSUE TITLE
Can't run project with `cargo run` on OSX

### ISSUE THREAD

**Issue by shusson** [arrayfire/arrayfire-rust#97] opened 2017-01-11 23:59 UTC
Platform: macOS 10.12.2
Cargo: cargo 0.15.0-nightly (298a012 2016-12-20)
Rust: rustc 1.14.0 (e8a012324 2016-12-16)

I've set up a rust project using crates but I'm getting no backends if I use `cargo run`, if I run the executable directly from the shell, I get expected results.

```
cargo run --example unified
   Compiling arrayfire v3.4.1 (file:///Users/shane/src/rust/arrayfire-rust)
    Finished debug [unoptimized + debuginfo] target(s) in 0.27 secs
     Running `target/debug/examples/unified`
There are 0 available backends

cargo build --example unified
    Finished debug [unoptimized + debuginfo] target(s) in 0.0 secs

./target/debug/examples/unified
There are 2 available backends
Evaluating CPU Backend...
There are 1 CPU compute devices
...
```

I've added a stackoverflow question with similar info  http://stackoverflow.com/questions/41602744/how-to-configure-arrayfire-rust-to-use-cargo-run

**Comment by pavanky** [comment] 2017-01-12 00:09
Are the arrayfire examples running fine ?

**Comment by shusson** [comment] 2017-01-12 00:14
not with `cargo run` 

```
cargo run --example unified
   Compiling arrayfire v3.4.1 (file:///Users/shane/src/rust/arrayfire-rust)
    Finished debug [unoptimized + debuginfo] target(s) in 0.27 secs
     Running `target/debug/examples/unified`
There are 0 available backends
```

**Comment by pavanky** [comment] 2017-01-12 00:21
@shusson I mean the C++ examples. Do they work ?

**Comment by shusson** [comment] 2017-01-12 00:24
oh yes they do, and if I build the arrayfire-rust examples and then run them directly they work as well

```
cargo build --example unified
    Finished debug [unoptimized + debuginfo] target(s) in 0.0 secs

./target/debug/examples/unified
There are 2 available backends
Evaluating CPU Backend...
There are 1 CPU compute devices
ArrayFire v3.5.0 (CPU, 64-bit Mac OSX, build b61de89)
[0] Intel: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz, 16384 MB, Max threads(8)
Create a 10-by-10 matrix of random floats on the compute device
...
```

**Comment by pavanky** [comment] 2017-01-12 00:27
@9prady9 Does the rust wrapper depend on the full version (i.e. `libaf.so.3.4.0` as opposed to `libaf.so.3` ?)

**Comment by 9prady9** [comment] 2017-01-12 01:13
@pavanky no, we don't use version specific symbols.

@shusson I am looking into the problem. What did you mean they run fine
from shell directly? Is the rust example executable running from shell but
not if do "Cargo run"?

**Comment by shusson** [comment] 2017-01-12 01:17
As in if I build an example with `cargo build --example unified` and then execute the program with my shell `./target/debug/examples/unified` everything works as expected. But if I try 'cargo run' no backends are found. My previous comments have examples.

**Comment by 9prady9** [comment] 2017-01-12 02:50
@shusson What is the output of `cargo run --example helloworld` instead of the unified example, does it also have the same problem ?

**Comment by shusson** [comment] 2017-01-12 02:51
all the other examples I've tried segfault

**Comment by 9prady9** [comment] 2017-01-12 03:00
@shusson Unfortunately i am unable to reproduce this problem on my end. @jramapuram Can you please check if you can reproduce this issue on OSX.

**Comment by pavanky** [comment] 2017-01-12 04:02
@mlloreda can you have a look too ?

@shusson It'll be helpful if you can update the original description with info about rust, rust-cargo  versions.

**Comment by shusson** [comment] 2017-01-12 04:07
sure, I've updated the original description with versions and example output

**Comment by jramapuram** [comment] 2017-01-19 01:15
@9prady9 : Been using Linux mostly now. Just download the binaries from [here](http://arrayfire.s3.amazonaws.com/index.html#!/3.4.1%2F) and tested on OSX and am seeing this issue too. Will try on a compiled version and report back.

**Comment by 9prady9** [comment] 2017-01-19 04:52
The compiled version should at least work, i hope so, because our build system for OSX didn't fail while compiling or running tests.

**Comment by jramapuram** [comment] 2017-01-25 02:36
This is very strange... It works fine when I run the example standalone, but not with cargo [both debug and release builds]. Issue is OSX only as far a I can tell.

I tried this with both the manually built version as well as the one I downloaded:

```bash
➜  jramapuram@gauss arrayfire-rust git:(master) cargo run --example helloworld
    Finished debug [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/examples/helloworld`
error: Process didn't exit successfully: `target/debug/examples/helloworld` (signal: 11, SIGSEGV: invalid memory reference)
```

Here is the backtrace:
```bash
➜  jramapuram@gauss arrayfire-rust git:(master) RUST_BACKTRACE=1 cargo run --release --example helloworld
    Finished release [optimized] target(s) in 0.0 secs
     Running `target/release/examples/helloworld`
thread 'main' panicked at 'Error message: Function returned successfully', src/error.rs:72
stack backtrace:
   1:        0x10d401809 - std::sys::backtrace::tracing::imp::write::hd4b54a4a2078cb15
   2:        0x10d403600 - std::panicking::default_hook::_{{closure}}::h51a5ee7ba6a9fcef
   3:        0x10d402a40 - std::panicking::default_hook::hf823fce261e27590
   4:        0x10d403066 - std::panicking::rust_panic_with_hook::h8d486474663979b9
   5:        0x10d402eb4 - std::panicking::begin_panic::h72862f004a4942ab
   6:        0x10d402e12 - std::panicking::begin_panic_fmt::hdc424a357d9142e1
   7:        0x10d3fb623 - fn(defines..AfError) {error..handle_error_general}::fn_pointer_shim.13566::h49ae5820a48a1a91
   8:        0x10d3fa8ff - arrayfire::error::HANDLE_ERROR::h6e6e246d93286b73
   9:        0x10d3f85ba - helloworld::main::h28638f4afa0da596
  10:        0x10d403bea - __rust_maybe_catch_panic
  11:        0x10d40250e - std::rt::lang_start::hca48e539ce72a288
error: Process didn't exit successfully: `target/release/examples/helloworld` (exit code: 101)
```

```bash
➜  jramapuram@gauss arrayfire-rust git:(master) ./target/debug/examples/helloworld
ArrayFire v3.4.0 (CUDA, 64-bit Mac OSX, build 10d9716)
Platform: CUDA Toolkit 8, Driver: CUDA Driver Version: 8000
[0] GeForce GT 750M, 2048 MB, CUDA Compute 3.0
Create a 5-by-3 matrix of random floats on the GPU
[5 3 1 1]
    0.3990     0.5160     0.8831
    0.6720     0.3932     0.0621
    0.5339     0.2706     0.7089
    0.1386     0.9455     0.9434
    0.7353     0.1587     0.1227

Element-wise arithmetic
sin(a) + 1.5 =>
[5 3 1 1]
    1.8885     1.9934     2.2727
    2.1226     1.8831     1.5621
    2.0089     1.7674     2.1510
    1.6381     2.3108     2.3096
    2.1708     1.6580     1.6224

sin(a) + cos(a) =>
[5 3 1 1]
    1.3100     1.3632     1.4075
    1.4051     1.3068     1.0601
    1.3697     1.2310     1.4101
    1.1285     1.3961     1.3966
    1.4124     1.1455     1.1149

!a =>
[5 3 1 1]
         0          0          0
         0          0          0
         0          0          0
         0          0          0
         0          0          0

a + b
[5 3 1 1]
    2.2876     2.5094     3.1558
    2.7945     2.2763     1.6242
    2.5427     2.0380     2.8599
    1.7767     3.2562     3.2529
    2.9060     1.8168     1.7452

a(seq(1,3,1), span)
[3 3 1 1]
    0.6720     0.3932     0.0621
    0.5339     0.2706     0.7089
    0.1386     0.9455     0.9434

a(indices, seq(0, 2, 1))
[3 3 1 1]
    0.6720     0.3932     0.0621
    0.5339     0.2706     0.7089
    0.1386     0.9455     0.9434

Fourier transform the result

[5 3 1 1]
         (9.8289,0.0000)          (9.6127,0.0000)          (9.9178,0.0000)
         (0.2648,-0.1720)          (-0.2116,0.1053)          (-0.3519,0.1506)
         (-0.4579,0.3809)          (0.3887,-0.6491)          (1.0748,-0.1153)
         (-0.4579,-0.3809)          (0.3887,0.6491)          (1.0748,0.1153)
         (0.2648,0.1720)          (-0.2116,-0.1053)          (-0.3519,-0.1506)

Grab last row & col of the random matrix

[5 3 1 1]
    0.3990     0.5160     0.8831
    0.6720     0.3932     0.0621
    0.5339     0.2706     0.7089
    0.1386     0.9455     0.9434
    0.7353     0.1587     0.1227


[1 3 1 1]
    0.7353     0.1587     0.1227

[5 1 1 1]
    0.8831
    0.0621
    0.7089
    0.9434
    0.1227

Set last row to 1's
[5 3 1 1]
    0.3990     0.5160     0.8831
    0.6720     0.3932     0.0621
    0.5339     0.2706     0.7089
    0.1386     0.9455     0.9434
    1.0000     1.0000     1.0000

Create 2-by-3 matrix from host data
[2 3 1 1]
         1          3          5
         2          4          6

Sort A and print sorted array and corresponding indices

[5 3 1 1]
    0.1386     0.1587     0.0621
    0.3990     0.2706     0.1227
    0.5339     0.3932     0.7089
    0.6720     0.5160     0.8831
    0.7353     0.9455     0.9434


[5 3 1 1]
         3          4          1
         0          2          4
         2          1          2
         1          0          0
         4          3          3

u8 constant array
[5 3 1 1]
         1          1          1
         1          1          1
         1          1          1
         1          1          1
         1          1          1

Is u8_cnst array float precision type ? false
```

**Comment by 9prady9** [comment] 2017-01-25 04:27
perhaps it is related to cargo on OSX ?

**Comment by 9prady9** [comment] 2017-01-25 11:56
@jramapuram Can you try `gdb --args cargo run --example helloworld` ?

**Comment by 9prady9** [comment] 2017-01-25 11:57
I wonder if the error handler is the culprit !?

**Comment by jramapuram** [comment] 2017-01-25 12:00
There is no gdb on OSX as it uses clang & thus lldb.
```
➜  jramapuram@gauss arrayfire-rust git:(master) lldb cargo
(lldb) target create "cargo"
Current executable set to 'cargo' (x86_64).
(lldb) r run --example helloworld
Process 83531 launched: '/Users/jramapuram/.cargo/bin/cargo' (x86_64)
    Finished debug [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/examples/helloworld`
error: Process didn't exit successfully: `target/debug/examples/helloworld` (signal: 11, SIGSEGV: invalid memory reference)
Process 83531 exited with status = 101 (0x00000065)
(lldb) bt
error: invalid thread
```

**Comment by 9prady9** [comment] 2017-01-25 12:02
I never used lldb, any idea why we can't see proper `bt` ?

**Comment by shepmaster** [comment] 2017-01-25 20:15
In that last case, cargo has forked the actual process, which failed. You need to attach to the forked process to catch the error there.

**Comment by 9prady9** [comment] 2017-02-26 06:51
@shusson Are you still facing this issue ?

**Comment by shusson** [comment] 2017-02-28 06:51
@9prady9  I was just trying out arrayfire-rust, if I revisit it I'll let you know.

**Comment by 9prady9** [comment] 2017-04-27 07:17
@shusson Cargo has moved to 0.17.* nightly and rustc has also updated about a month back. Can you give newer cargo version a try and reopen the issue if the problem still persists. I am closing the issue for now.

**Closed by 9prady9** 2017-04-27 07:17 UTC
Labels: OSX
